### ISSUE TITLE
Mobile : investiguer la librairie facebook conceal (permet de chiffrer du contenu sur le téléphone)

### ISSUE THREAD

**Issue by lribiere** [Aura-healthcare/Aura_gitbook#10]

**Comment by clecoued** [comment]
completed with commit -> [https://github.com/Aura-healthcare/Aura_mobile_app/commit/7930d7561ee8b53aa1b412575182bf495f3cb1cb](https://github.com/Aura-healthcare/Aura_mobile_app/commit/7930d7561ee8b53aa1b412575182bf495f3cb1cb)
